In [17]:
 import pandas as pd

In [36]:
df = pd.read_csv("financial_dataset.csv")

In [37]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [38]:
df.shape

(2000, 10)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    2000 non-null   int64
 1   Customer_ID       2000 non-null   str
 2   Customer_Name     2000 non-null   str
 3   Category          1977 non-null   str
 4   Sales             1967 non-null   float64
 5   Profit            1970 non-null   float64
 6   Quantity          2000 non-null   int64
 7   Payment_Status    2000 non-null   str
 8   City              1979 non-null   str
 9   Transaction_Date  2000 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 259.3 KB

In [40]:
df.describe()

       Transaction_ID         Sales        Profit    Quantity
count     2000.000000   1967.000000   1970.000000  2000.00000
mean     11001.443500  25147.046263   3469.098985    10.18850
std        578.772536  14375.624741   4923.386360     5.52958
min      10001.000000    516.000000  -4982.000000     1.00000
25%      10502.750000  12723.500000   -812.500000     5.00000
50%      10998.500000  25200.000000   3526.000000    10.00000
75%      11504.250000  37545.000000   7711.250000    15.00000
max      12000.000000  49923.000000  11988.000000    19.00000

In [29]:
df.head()

,Company,Current_Assets,Current_Liabilities,Net_Income,Shareholders_Equity,Outstanding_Shares
0,ABC Ltd,500000,250000,100000,400000,50000
1,XYZ Ltd,800000,400000,150000,600000,75000
2,PQR Ltd,300000,200000,50000,250000,25000
3,LMN Ltd,1000000,500000,200000,800000,100000
4,DEF Ltd,450000,300000,75000,350000,50000

In [30]:
df.tail()

,Company,Current_Assets,Current_Liabilities,Net_Income,Shareholders_Equity,Outstanding_Shares
10,Alpha Ltd,480000,240000,96000,320000,48000
11,Beta Ltd,850000,425000,170000,680000,85000
12,Gamma Ltd,620000,310000,124000,500000,62000
13,Delta Ltd,400000,200000,80000,300000,40000
14,Omega Ltd,1100000,550000,220000,900000,110000

In [32]:
df.isnull().sum()

Company                0
Current_Assets         0
Current_Liabilities    0
Net_Income             0
Shareholders_Equity    0
Outstanding_Shares     0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [41]:
df["Category"] = df["Category"].fillna(df["Category"].mode()[0])
df["Profit"] = df["Profit"].fillna(df["Profit"].mean())
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [42]:
df.isnull().sum()

Transaction_ID      0
Customer_ID         0
Customer_Name       0
Category            0
Sales               0
Profit              0
Quantity            0
Payment_Status      0
City                0
Transaction_Date    0
dtype: int64

In [43]:
df = df.drop_duplicates()

In [45]:
df["Category"] = df["Category"].str.strip().str.title()
df["Payment_Status"] = df["Payment_Status"].str.strip().str.title()
df["City"] = df["City"].str.strip().str.title()

In [46]:
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"])

In [47]:
(df.dtypes)

Transaction_ID               int64
Customer_ID                    str
Customer_Name                  str
Category                       str
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status                 str
City                           str
Transaction_Date    datetime64[us]
dtype: object

In [54]:
print("Cleaned Financial Dataset")
df

Cleaned Financial Dataset

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [55]:
df.to_csv("cleaned_financial_dataset.csv", index=False)
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00